### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by gusty** [weblinq/WebLinq#5] opened 2016-10-31 14:36 UTC
It would be nice to have more examples showing the features of WebLinq queries.

**Comment by gmpl** [comment] 2016-11-04 12:36
[Here's](https://gist.github.com/gmpl/f8ac85f29b7a36096aba99abbd97690d) a simple one

**Comment by atifaziz** [comment] 2016-11-05 17:07
@gmpl Nice one! Let's add that to the [current set of examples](https://github.com/atifaziz/WebLinq/blob/8956e4a487d13b638307ccc67b92ab4a8b9208a1/eg/Program.cs). Want to send a PR?

**Comment by underwater** [comment] 2016-11-20 12:23
I have tried to write a simple parser to read of stock price history from NASDAQ just to get a feel for the basic methods exposed on IQuery.      Am I on the right track or is there a better way for this sort of parsing ?
`static class Program
    {
        public static void Main()
        {
            string symbol = "v";            // VISA Stock Symbol
            GetNasdaqPrices(symbol);
        }


        static void GetNasdaqPrices(string symbol)
        {
            // Historical Prices Site (NASDAQ)
            string url = $"http://www.nasdaq.com/symbol/{symbol}/historical";

            var html = Http.Get(new Uri(url))
                .Html().Content()
                .GetResult(DefaultQueryContext.Create())
                .First().Value;
          
            var table = html.Tables("*").Skip(5).Take(1);

            var rows = table.SelectMany(i => i.QuerySelectorAll("tr")).ToList();

            var prices = rows.Skip(2).Select(r =>  new { Date = GetDate(r), Price = GetPrice(r)});

        }

         static string GetDate(HtmlObject r) => r.QuerySelectorAll("td").Take(1).First().InnerTextSource.Decoded.Trim();
         static string GetPrice(HtmlObject r) => r.QuerySelectorAll("td").Skip(4).Take(1).First().InnerTextSource.Decoded.Trim();

    }`

**Comment by atifaziz** [comment] 2016-11-20 14:20
@underwater You're on the right track but you can simplify into a single query…

```c#
static void GetNasdaqPrices(string symbol)
{
    // Historical Prices Site (NASDAQ)
    string url = $"http://www.nasdaq.com/symbol/{symbol}/historical";

    var data =
        from html in Http.Get(new Uri(url)).Html().Content()
        from table in html.Tables("#historicalContainer table")
        from row in table.QuerySelectorAll("tr")
        let cells = row.QuerySelectorAll("td").Select(td => td.InnerText).ToArray()
        where cells.Length == 6
        select new
        {
            Date   = cells[0].Trim(),
            Open   = cells[1].Trim(),
            High   = cells[2].Trim(),
            Low    = cells[3].Trim(),
            Close  = cells[4].Trim(),
            Volume = cells[5].Trim(),
        }
        into row
        where row.Date.Length > 0 // skip invalid rows
        select row;
}
```

Note that to select the right table, I use the selector `#historicalContainer table` as I noticed on the web page that the prices table is sitting in a `div` with an Id of `historicalContainer`.

**Comment by gmpl** [comment] 2016-11-21 17:39
Nice @underwater I did [an F# version of your scrape](https://github.com/gmpl/WebLinq/blob/fsharp/WebLinq.FsSamples/Program.fs) to see how would it look like.
@atifaziz Do you have any idea why it doesn't work in F# scripts?

**Comment by atifaziz** [comment] 2016-11-22 11:14
> why it doesn't work in F# scripts?

@gmpl Would be good to have more info than “it doesn't work.” I see that [you have added the F# sample to your fork](https://github.com/gmpl/WebLinq/blob/871b9bbd97bb2ea4be904a3ee6a076b959f47f6d/WebLinq.FsSamples/Program.fs) so could you debug through and share more details? While I have a cursory understanding of F# builders, I have yet to write one so I'm not in a position to help immediately. Since [it works with LINQ in C#](https://github.com/weblinq/WebLinq/issues/5#issuecomment-261781064), my uneducated guess is that it may have something to do with the builder in F# and following the needed rules.

**Comment by gmpl** [comment] 2016-11-22 13:04
> Would be good to have more info than “it doesn't work.”

By sniffing the traffic it seems the request succeed but the script never ends the execution.

>  I see that you have added the F# sample to your fork so could you debug through and share more details?

Yes, but what's the point on debugging code that actually works?

> Since it works with LINQ in C#, my uneducated guess is that it may have something to do with the builder in F# and following the needed rules.

I don't think it has anything to do with the builders. Not even with F#, since apparently the same behavior is observed in C# Interactive with your C# code.

I can certainly investigate, just wanted to know if you find this behavior expected for some reason or if you had already an idea of what's wrong with scripts.

**Comment by atifaziz** [comment] 2016-11-22 13:23
>  apparently the same behavior is observed in C# Interactive with your C# code.

Okay so this is new info because your [initial comment said it didn't work with F# scripts](https://github.com/weblinq/WebLinq/issues/5#issuecomment-262010681) so I assumed the C# code is at least working. Could you open that as a new issue?

**Comment by gmpl** [comment] 2016-11-22 13:32
Yes, I said F# scripts because I wasn't sure about the C# scripts but by observing the behavior I suspected that might fail in C# as well.
But after your reply I tried to reproduce it in C# and indeed it also hangs.
So here's [the issue](https://github.com/weblinq/WebLinq/issues/15)

**Comment by atifaziz** [comment] 2019-07-16 17:05
I think this is [fairly covered](https://github.com/weblinq/WebLinq/blob/483f1c8915472b75f6c78543113262cdc8bbd46f/eg/Program.cs) so closing this for now. Going forward, we can open issues for examples of specific features still uncovered.

**Closed by atifaziz** 2019-07-16 17:05 UTC
